import {
  Music,
  TrendingUp,
  Bot,
  Camera,
  Code2,
  Database,
  Globe,
  Palette,
  Presentation,
  Shield,
  Terminal,
  FileText,
  Zap,
  BarChart3,
  BookOpen,
  Cpu,
  Video,
  HardDrive,
} from 'lucide-react'
import type { Feature, Category } from '../types/features'

export const categories: Category[] = [
  '全部',
  '开发工具',
  'AI 工具',
  '金融理财',
  '影音媒体',
  '效率办公',
  '教育学习',
]

/**
 * Central configuration for all features/tools.
 * To add a new feature, simply append an object to this array.
 */
export const featuresConfig: Feature[] = [
  // ---- 已上线 (active) ----
  {
    id: 'temp-drive',
    title: '临时网盘',
    description: '上传文件获取取件码，凭码提取下载，24 小时有效',
    icon: HardDrive,
    category: '效率办公',
    status: 'active',
    accentColor: '#0ea5e9',
  },
  {
    id: 'ai-ppt-generator',
    title: 'AI 演示文稿生成器',
    description: '神经符号引擎自动生成专业演示文稿',
    icon: Presentation,
    category: 'AI 工具',
    status: 'active',
    accentColor: '#f43f5e',
  },
  {
    id: 'music-player',
    title: '音乐播放器',
    description: '在线播放与管理个人音乐库',
    icon: Music,
    category: '影音媒体',
    status: 'active',
    accentColor: '#ec4899',
  },
  {
    id: 'video-extractor',
    title: '视频提取器',
    description: '输入抖音链接，提取无水印原视频下载地址',
    icon: Video,
    category: '影音媒体',
    status: 'active',
    accentColor: '#e11d48',
  },
  // ---- 未上线 (coming-soon) ----
  {
    id: 'stock-tracker',
    title: '股票追踪',
    description: '实时投资组合监控与市场分析',
    icon: TrendingUp,
    category: '金融理财',
    status: 'coming-soon',
    accentColor: '#10b981',
  },
  {
    id: 'ai-assistant',
    title: 'AI 智能助手',
    description: '基于大语言模型的智能对话',
    icon: Bot,
    category: 'AI 工具',
    status: 'coming-soon',
    accentColor: '#6366f1',
  },
  {
    id: 'photo-editor',
    title: '图片编辑器',
    description: '浏览器内图像编辑与增强处理',
    icon: Camera,
    category: '影音媒体',
    status: 'coming-soon',
    accentColor: '#f59e0b',
  },
  {
    id: 'code-playground',
    title: '代码沙盒',
    description: '在浏览器中编写、运行和分享代码片段',
    icon: Code2,
    category: '开发工具',
    status: 'coming-soon',
    accentColor: '#3b82f6',
  },
  {
    id: 'api-tester',
    title: 'API 测试工具',
    description: '测试与调试 REST 和 GraphQL 接口',
    icon: Terminal,
    category: '开发工具',
    status: 'coming-soon',
    accentColor: '#8b5cf6',
  },
  {
    id: 'data-dashboard',
    title: '数据看板',
    description: '通过交互式图表可视化数据集',
    icon: BarChart3,
    category: '金融理财',
    status: 'coming-soon',
    accentColor: '#06b6d4',
  },
  {
    id: 'ai-image-gen',
    title: 'AI 图像生成器',
    description: '通过文字描述生成 AI 图像',
    icon: Palette,
    category: 'AI 工具',
    status: 'coming-soon',
    accentColor: '#d946ef',
  },
  {
    id: 'study-notes',
    title: '学习笔记',
    description: '整理笔记并通过间隔重复法复习',
    icon: BookOpen,
    category: '教育学习',
    status: 'coming-soon',
    accentColor: '#14b8a6',
  },
  {
    id: 'db-explorer',
    title: '数据库浏览器',
    description: '通过可视化界面浏览和查询数据库',
    icon: Database,
    category: '开发工具',
    status: 'coming-soon',
    accentColor: '#f97316',
  },
  {
    id: 'web-scraper',
    title: '网页采集器',
    description: '从任意网页提取结构化数据',
    icon: Globe,
    category: '开发工具',
    status: 'coming-soon',
    accentColor: '#64748b',
  },
  {
    id: 'security-scanner',
    title: '安全扫描器',
    description: '审计项目中的常见安全漏洞',
    icon: Shield,
    category: '开发工具',
    status: 'coming-soon',
    accentColor: '#ef4444',
  },
  {
    id: 'doc-generator',
    title: '文档生成器',
    description: '从代码库自动生成项目文档',
    icon: FileText,
    category: '效率办公',
    status: 'coming-soon',
    accentColor: '#84cc16',
  },
  {
    id: 'task-automator',
    title: '任务自动化',
    description: '创建自动化工作流和定时任务',
    icon: Zap,
    category: '效率办公',
    status: 'coming-soon',
    accentColor: '#eab308',
  },
  {
    id: 'ml-playground',
    title: '机器学习实验室',
    description: '训练和实验机器学习模型',
    icon: Cpu,
    category: 'AI 工具',
    status: 'coming-soon',
    accentColor: '#7c3aed',
  },
]
