import {
  Music,
  TrendingUp,
  Bot,
  Camera,
  Code2,
  Database,
  Globe,
  Palette,
  Shield,
  Terminal,
  FileText,
  Zap,
  BarChart3,
  BookOpen,
  Cpu,
  Video,
} from 'lucide-react'
import type { Feature, Category } from '../types/features'

export const categories: Category[] = [
  'All',
  'Development',
  'AI Tools',
  'Finance',
  'Media',
  'Productivity',
  'Education',
]

/**
 * Central configuration for all features/tools.
 * To add a new feature, simply append an object to this array.
 */
export const featuresConfig: Feature[] = [
  {
    id: 'music-player',
    title: 'Music Player',
    description: 'Stream and manage your personal music library',
    icon: Music,
    category: 'Media',
    status: 'active',
    accentColor: '#ec4899',
  },
  {
    id: 'stock-tracker',
    title: 'Stock Tracker',
    description: 'Real-time portfolio monitoring and market analysis',
    icon: TrendingUp,
    category: 'Finance',
    status: 'active',
    accentColor: '#10b981',
  },
  {
    id: 'ai-assistant',
    title: 'AI Assistant',
    description: 'Intelligent chat powered by large language models',
    icon: Bot,
    category: 'AI Tools',
    status: 'active',
    accentColor: '#6366f1',
  },
  {
    id: 'photo-editor',
    title: 'Photo Editor',
    description: 'Browser-based image editing and enhancement',
    icon: Camera,
    category: 'Media',
    status: 'beta',
    accentColor: '#f59e0b',
  },
  {
    id: 'code-playground',
    title: 'Code Playground',
    description: 'Write, run, and share code snippets in the browser',
    icon: Code2,
    category: 'Development',
    status: 'active',
    accentColor: '#3b82f6',
  },
  {
    id: 'api-tester',
    title: 'API Tester',
    description: 'Test and debug REST & GraphQL endpoints',
    icon: Terminal,
    category: 'Development',
    status: 'beta',
    accentColor: '#8b5cf6',
  },
  {
    id: 'data-dashboard',
    title: 'Data Dashboard',
    description: 'Visualize datasets with interactive charts',
    icon: BarChart3,
    category: 'Finance',
    status: 'coming-soon',
    accentColor: '#06b6d4',
  },
  {
    id: 'ai-image-gen',
    title: 'AI Image Generator',
    description: 'Generate images from text prompts using AI',
    icon: Palette,
    category: 'AI Tools',
    status: 'coming-soon',
    accentColor: '#d946ef',
  },
  {
    id: 'study-notes',
    title: 'Study Notes',
    description: 'Organize and review notes with spaced repetition',
    icon: BookOpen,
    category: 'Education',
    status: 'active',
    accentColor: '#14b8a6',
  },
  {
    id: 'db-explorer',
    title: 'DB Explorer',
    description: 'Browse and query databases with a visual interface',
    icon: Database,
    category: 'Development',
    status: 'coming-soon',
    accentColor: '#f97316',
  },
  {
    id: 'web-scraper',
    title: 'Web Scraper',
    description: 'Extract structured data from any webpage',
    icon: Globe,
    category: 'Development',
    status: 'coming-soon',
    accentColor: '#64748b',
  },
  {
    id: 'security-scanner',
    title: 'Security Scanner',
    description: 'Audit your projects for common vulnerabilities',
    icon: Shield,
    category: 'Development',
    status: 'coming-soon',
    accentColor: '#ef4444',
  },
  {
    id: 'doc-generator',
    title: 'Doc Generator',
    description: 'Auto-generate documentation from your codebase',
    icon: FileText,
    category: 'Productivity',
    status: 'beta',
    accentColor: '#84cc16',
  },
  {
    id: 'task-automator',
    title: 'Task Automator',
    description: 'Create automated workflows and scheduled tasks',
    icon: Zap,
    category: 'Productivity',
    status: 'coming-soon',
    accentColor: '#eab308',
  },
  {
    id: 'video-editor',
    title: 'Video Editor',
    description: 'Trim, merge, and export video clips in-browser',
    icon: Video,
    category: 'Media',
    status: 'coming-soon',
    accentColor: '#e11d48',
  },
  {
    id: 'ml-playground',
    title: 'ML Playground',
    description: 'Train and experiment with machine learning models',
    icon: Cpu,
    category: 'AI Tools',
    status: 'coming-soon',
    accentColor: '#7c3aed',
  },
]
